name: Release on dd.js Change

on:
  push:
    paths:
      - 'x/**'
      - 'src/dd/**'
      - '.github/workflows/**'

permissions:
  contents: write

jobs:
  release_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch tags
      run: |
        git fetch --tags

    - name: Create date-fifo tag
      id: find_date_fifo
      run: |
        TAGS=(
          "main$(date -u +'%y.%m.%d')"
          "main$(date -u +'%y.%m.%d.%H')"
          "main$(date -u +'%y.%m.%d.%H.%M')"
          "main$(date -u +'%y.%m.%d.%H.%M.%S')"
        )

        for TAG in "${TAGS[@]}"; do
          if ! git tag -l | grep -q "^$TAG$"; then
            echo "Found tag: $TAG"
            echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV
            exit 0
          fi
        done
        echo "All possible tags already exist."
        exit 1

    - name: Check if relevant files changed
      id: dd_is_modified
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^src/dd/'; then
          echo "must make new dd.js files"
          echo "files_changed=true" >> $GITHUB_ENV
        fi

    - name: esbuild dd.js
      if: env.files_changed == 'true'
      run: |
        npx esbuild src/dd/dd.js \
          --bundle \
          --outfile=dd.js \
          --format=iife \
          --target=es2018 \
          --sourcemap \
          --minify
    
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: "Release ${{ env.RELEASE_TAG }}"
        tag: "${{ env.RELEASE_TAG }}"
