name: Release on dd.js Change

on:
  push:
    paths:
      - 'dd.js'  # Only trigger when dd.js is modified

permissions:
  contents: write

jobs:
  release_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get current time in GMT
      id: datetime
      run: |
        # Get the current time in GMT
        echo "YY=$(date -u +'%y')" >> $GITHUB_ENV
        echo "YYMM=$(date -u +'%y.%m')" >> $GITHUB_ENV
        echo "YYMMDD=$(date -u +'%y.%m.%d')" >> $GITHUB_ENV
        echo "YYMMDD_HH=$(date -u +'%y.%m.%d.%H')" >> $GITHUB_ENV
        echo "YYMMDD_HHMM=$(date -u +'%y.%m.%d.%H.%M')" >> $GITHUB_ENV
        echo "YYMMDD_HHMMSS=$(date -u +'%y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV

    - name: Determine the shortest available tag
      id: determine_tag
      run: |
        # Define possible tags in order of priority
        TAGS=(
          "main${{ env.YY }}"
          "main${{ env.YYMM }}"
          "main${{ env.YYMMDD }}"
          "main${{ env.YYMMDD_HH }}"
          "main${{ env.YYMMDD_HHMM }}"
          "main${{ env.YYMMDD_HHMMSS }}"
        )
        
        # Loop through tags and find the first one that doesn't exist
        for TAG in "${TAGS[@]}"; do
          if ! git tag -l | grep -q "^$TAG$"; then
            echo "Found tag: $TAG"
            echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV
            exit 0
          fi
        done
        # If all tags exist, exit with error
        echo "All possible tags already exist."
        exit 1

    - uses: actions/checkout@v3
    
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: "Release ${{ env.RELEASE_TAG }}"
        tag: "${{ env.RELEASE_TAG }}"
